Fixes for SF3.4
zicht/filemanager-bundle pull request #15
Opened 2018-06-01 06:07 UTC by erik-zicht

TODO: create a new releasebranch when approved and update README and CHANGELOG

2018-06-20 11:37 UTC, pbergman requested changes

2018-06-20 11:37 UTC, pbergman commented on src/Zicht/Bundle/FileManagerBundle/Form/FileType.php
> +                \Symfony\Component\Form\Extension\Core\Type\FileType::class,
we do not use full namespaces

2018-06-20 11:40 UTC, erik-zicht commented on src/Zicht/Bundle/FileManagerBundle/Form/FileType.php
> +                \Symfony\Component\Form\Extension\Core\Type\FileType::class,
No but this class is already called "FileType". I prefer this over a use-statement with an alias.

2018-06-25 12:20 UTC, pbergman approved these changes

2018-06-26 12:41 UTC, merged